name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Use Python 3.12

      # Step 3: Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # Step 4: Install dependencies (including dev dependencies)
      - name: Install dependencies
        run: poetry install --no-root --no-interaction --no-ansi --with dev

      # Step 5: Run tests with coverage
      - name: Run tests and generate coverage
        run: poetry run pytest tests/ --cov=src --cov-report=term-missing --cov-report=xml
